convert src/jetpack.png -resize 250x jetpack.png
convert src/plume.png -resize 250x plume.png
convert src/pickle.png -resize 200x pickle.png
convert src/ketchup.png -resize x300 ketchup.png
convert src/player.png -resize x560 player.png
